
---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: rhacm-posthook-linux-hello-world
  namespace: simpleweb
  labels:
    app.kubernetes.io/name: simpleweb
spec:
  tower_auth_secret: toweraccess
  job_template_name: rhacm_posthook_linux_hello_world
  extra_vars:
    app_name: simpleweb
    message: "Updated by Red Hat Advanced Cluster Management for Kubernetes"
